config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  post "/reset", to: "pages#reset", as: 'reset'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :poker_tables, only: %i[index show] do
    resources :players, only: [:create]
  end
  resources :players, only: [] do
    patch :leave, on: :member
  end
  resources :player_hands, only: [] do
    member do
      patch :call_hand
      patch :raise_hand
      patch :fold_hand
    end
  end
  resources :table_hands, only: [:create] do
    patch :reinitialize, on: :member, as: "reinitialize"
    patch :flop
    patch :turn
    patch :river
    patch :back
  end
end

app/views/shared/_banner.html.erb
<div class="banner mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url(<%= asset_path 'poker_background.jpg' %>);">
  <div class="container">
    <div class="d-flex align-items-end justify-content-center">
      <h1 class="text-end"><strong>Welcome to </strong></h1>
      <%= image_tag "GL_logo_white_on_black.png", id: 'logo-banner' %>
    </div>
    <p>Trust your skills not your luck</p>
    <%= link_to "Find a table", poker_tables_path, class: "btn btn-flat" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-good-luck-poker.svg", alt: "logo good luck poker" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item dropdown ms-3">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, alt: "Picture of #{current_user.nickname}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://avatars.dicebear.com/api/micah/#{current_user.nickname}.svg?background=%231A8A47", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-dark dropdown-menu-end" aria-labelledby="navbarDropdown">
              <span class="dropdown-item disabled"><small class="text-uppercase">Balance:</small> <strong class="text-info"><%= current_user.balance %></strong> <i class="fa-solid fa-coins text-info"></i></span>
              <span class="dropdown-item disabled"><small class="text-uppercase">Luck ratio:</small> <strong class="text-white"><%= '%.2f' % current_user.luck_ratio %></strong> <% if current_user.increasing_luck %>
                  <i class="fa-solid fa-arrow-trend-up text-success"></i>
                <% else %>
                  <i class="fa-solid fa-arrow-trend-down text-danger"></i>
                <% end %></span>
                <hr class="dropdown-divider">
              <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Reset balance", reset_path, data: {turbo_method: :post, turbo_confirm: "Are you sure? (YOU WILL LOSE BALANCE IF >500)" }, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item text-danger" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>