config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  post "/reset", to: "pages#reset", as: 'reset'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :poker_tables, only: %i[index show] do
    resources :players, only: [:create]
  end
  resources :players, only: [] do
    patch :leave, on: :member
  end
  resources :player_hands, only: [] do
    member do
      patch :call_hand
      patch :raise_hand
      patch :fold_hand
    end
  end
  resources :table_hands, only: [:create] do
    patch :reinitialize, on: :member, as: "reinitialize"
    patch :flop
    patch :turn
    patch :river
    patch :back
  end
end

app/controllers/poker_tables_controller.rb
class PokerTablesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    if params[:max_players].present?
      @poker_tables = PokerTable.where(max_players: params[:max_players])
      @max_players = params[:max_players]
    elsif params[:small_blind].present?
      @poker_tables = PokerTable.where(small_blind: params[:small_blind])
      big_blind = params[:small_blind].to_i * 2
      @small_blind = "#{params[:small_blind]}-#{big_blind}"
    else
      @poker_tables = PokerTable.all
      @max_players = ""
      @small_blind = ""
    end
    @poker_table = PokerTable.new
  end

  def show
    @poker_table = PokerTable.find(params[:id])
    @players = @poker_table.players.active
    @positions = @players.map(&:position).sort
    @table_hand = @poker_table.table_hands.last
  end
end

app/views/poker_tables/_luck.html.erb
<div class="d-flex justify-content-between">
  <span>Luck ratio: <br><strong class="text-light"><%= '%.2f' % player.user.luck_ratio %></strong></span>
  <span>Trend: <br><% if player.user.increasing_luck %>
      <i class="fa-solid fa-arrow-trend-up text-success"></i>
    <% else %>
      <i class="fa-solid fa-arrow-trend-down text-danger"></i>
    <% end %>
  </span>
  </div>
<% if player.user.luck_ratio > 1.2 %>
  <em>A <strong>very</strong> lucky player</em>
  <div><i class="fa-solid fa-clover text-info"></i> <i class="fa-solid fa-clover text-info"></i> <i class="fa-solid fa-clover text-info"></i> <i class="fa-solid fa-clover text-info"></i> <i class="fa-solid fa-clover text-info"></i></div>
<% elsif player.user.luck_ratio > 1.1 %>
  <em>A lucky player</em>
  <div><i class="fa-solid fa-clover text-info"></i> <i class="fa-solid fa-clover text-info"></i> <i class="fa-solid fa-clover text-info"></i> <i class="fa-solid fa-clover text-info"></i> <i class="fa-solid fa-clover"></i></div>
<% elsif player.user.luck_ratio > 0.9 %>
  <em>Average player luck</em>
  <div><i class="fa-solid fa-clover text-info"></i> <i class="fa-solid fa-clover text-info"></i> <i class="fa-solid fa-clover text-info"></i> <i class="fa-solid fa-clover"></i> <i class="fa-solid fa-clover"></i></div>
<% elsif player.user.luck_ratio > 0.8 %>
  <em>An unlucky player</em>
  <div><i class="fa-solid fa-clover text-info"></i> <i class="fa-solid fa-clover text-info"></i> <i class="fa-solid fa-clover"></i> <i class="fa-solid fa-clover"></i> <i class="fa-solid fa-clover"></i></div>
<% else %>
  <em>A <strong>very</strong> unlucky player</em>
  <div><i class="fa-solid fa-clover text-info"></i> <i class="fa-solid fa-clover"></i> <i class="fa-solid fa-clover"></i> <i class="fa-solid fa-clover"></i> <i class="fa-solid fa-clover"></i></div>
<% end %>

app/views/poker_tables/_opponent_card.erb
<div>
  <div class="opponent-name">
    <%= player.user.nickname %>
  </div>
  <div class="opponent-cards">
    <%= image_tag "cards/#{player.player_hands.last.player_card1}.svg", class: 'opponent-card', id: 'opponent-card1' %>
    <%= image_tag "cards/#{player.player_hands.last.player_card2}.svg", class: 'opponent-card', id: 'opponent-card2' %>
  </div>
</div>

app/views/poker_tables/_player.html.erb
<div class="avatar-select <%= 'player-active' if !table_hand.nil? && table_hand.status != 'end' && player.position == table_hand.current_player_position %>">
  <div class="avatar-overlay <%= 'player-folded' if !table_hand.nil? && table_hand.status != 'end' && !player.player_hands.where(table_hand: table_hand).empty? && player.player_hands.find_by(table_hand: table_hand).folded == true %>">
    <% if player.user.photo.attached? %>
      <%= cl_image_tag player.user.photo.key, alt: "Picture of #{player.user.nickname}", class: "avatar-large"%>
    <% else %>
      <%= image_tag "https://avatars.dicebear.com/api/micah/#{player.user.nickname}.svg?background=%231A8A47", class: "avatar-large" %>
    <% end %>
  </div>
</div>
<div class="player-display-info">
  <h2><%= player.user.nickname %></h2>
  <% if !table_hand.nil? && table_hand.status != 'end' && !player.player_hands.where(table_hand: table_hand).empty? %>
    <p><small class="text-uppercase">Bet:</small> <strong class="text-success"><%= player.player_hands.find_by(table_hand: table_hand).bet_amount %></strong> / <%= player.stack %> <i class="fa-solid fa-coins"></i></p>
  <% else %>
    <p><small class="text-uppercase">Stack:</small> <%= player.stack %> <i class="fa-solid fa-coins"></i></p>
  <% end %>
</div>

app/views/poker_tables/_raise.html.erb
<div class="raisecontainer">
  <div class="range-slider" data-controller="raise" data-raise-max-value=<%= max %> data-raise-min-value=<%= min %> >
    <div class="mb-2">
      <%= link_to "fold", fold_hand_player_hand_path(player.player_hands.last.id), data: { turbo_method: :patch }, class: 'btn btn-action' %>
      <% if poker_table.table_hands.last.current_call_amount.zero? %>
        <% action_name = "check" %>
      <% elsif poker_table.table_hands.last.current_call_amount >= max %>
        <% action_name = "all-in" %>
      <% else %>
         <% action_name = "call" %>
      <% end %>
      <%= link_to action_name, call_hand_player_hand_path(player.player_hands.last.id), data: { turbo_method: :patch }, class: 'btn btn-action ms-2 call-action' %>
      <% if player.stack > poker_table.table_hands.last.current_call_amount %>
        <%= link_to "raise", raise_hand_player_hand_path(player.player_hands.last.id), raise_amount: "", data: { raise_target: "sender", turbo_method: :patch }, class: "btn btn-action ms-2 all-in" %>
      <% end %>
    </div>
    <% if player.stack > poker_table.table_hands.last.current_call_amount %>
      <form class="d-flex justify-content-between">
        <div class="d-flex">
          <label for="customRange" class="form-label mb-0">Raise:&nbsp;</label>
          <output class="raise__value"
                  data-raise-target="value">0</output>
        </div>
        <input type="range"
              name="customRange"
              class="raise__range ms-2"
              data-raise-target="range"
              data-action="input->raise#updateValue"
              value=<%= player.stack < (player.poker_table.small_blind * 2) ? player.stack : min.zero? ? (player.poker_table.small_blind * 2) : min %>
              min=<%= player.stack < (player.poker_table.small_blind * 2) ? player.stack : min.zero? ? (player.poker_table.small_blind * 2) : min %>
              max=<%= max %>
              step="1">
      </form>
     <% end %>
  </div>
</div>

<%# data-raise-target="range" %>

app/views/poker_tables/_seat_bottom.html.erb
<% if players.find_by(position: position).nil? %>
  <% if players.exclude?(player) && player.user.balance >= poker_table.small_blind * 100 && player.user.players.active.empty? %>
    <div class="join-seat seat-bottom">
      <%= link_to "Join seat", poker_table_players_path(poker_table, position: position), data: { turbo_method: :post }, class: 'stretched-link' %>
    </div>
  <% else %>
    <div class="available-seat seat-bottom">
      <p><%= position %></p>
    </div>
  <% end %>
<% else %>
  <div class="player-container player-container-bottom" data-controller="popper">
    <div class="player-display player-display-bottom <% if !table_hand.nil? && table_hand.status != 'end' %>
      <% if players.find_by(position: position).position == table_hand.first_player_position %>
        first-player-bottom
      <% elsif players.find_by(position: position).position == table_hand.positions[(table_hand.positions.index(table_hand.first_player_position) + 1) % players.count] %>
        second-player-bottom
      <% end %>
    <% end %>" data-popper-target="element" data-action="mouseenter->popper#show mouseleave->popper#hide">
      <div id="tooltip" role="tooltip" data-popper-target="tooltip">
        <%= render 'poker_tables/luck', player: players.find_by(position: position) %>
        <div id="arrow" data-popper-arrow></div>
      </div>
      <%= render 'poker_tables/player', player: players.find_by(position: position), table_hand: table_hand %>
    </div>
  </div>
<% end %>

app/views/poker_tables/_seat_left.html.erb
<% if players.find_by(position: position).nil? %>
  <% if players.exclude?(player) && player.user.balance >= poker_table.small_blind * 100 && player.user.players.active.empty? %>
    <div class="join-seat seat-left">
      <%= link_to "Join seat", poker_table_players_path(poker_table, position: position), data: { turbo_method: :post }, class: 'stretched-link' %>
    </div>
  <% else %>
    <div class="available-seat seat-left">
      <p><%= position %></p>
    </div>
  <% end %>
<% else %>
  <div class="player-container player-container-left" data-controller="popper">
    <div class="player-display player-display-left <% if !table_hand.nil? && table_hand.status != 'end' %>
      <% if players.find_by(position: position).position == table_hand.first_player_position %>
        first-player-left
      <% elsif players.find_by(position: position).position == table_hand.positions[(table_hand.positions.index(table_hand.first_player_position) + 1) % players.count] %>
        second-player-left
      <% end %>
    <% end %>" data-popper-target="element" data-action="mouseenter->popper#show mouseleave->popper#hide">
      <div id="tooltip" role="tooltip" data-popper-target="tooltip">
        <%= render 'poker_tables/luck', player: players.find_by(position: position) %>
        <div id="arrow" data-popper-arrow></div>
      </div>
      <%= render 'poker_tables/player', player: players.find_by(position: position), table_hand: table_hand %>
    </div>
  </div>
<% end %>

app/views/poker_tables/_seat_right.html.erb
<% if players.find_by(position: position).nil? %>
  <% if players.exclude?(player) && player.user.balance >= poker_table.small_blind * 100 && player.user.players.active.empty? %>
    <div class="join-seat seat-right">
      <%= link_to "Join seat", poker_table_players_path(poker_table, position: position), data: { turbo_method: :post }, class: 'stretched-link' %>
    </div>
  <% else %>
    <div class="available-seat seat-right">
      <p><%= position %></p>
    </div>
  <% end %>
<% else %>
  <div class="player-container player-container-right" data-controller="popper">
    <div class="player-display player-display-right <% if !table_hand.nil? && table_hand.status != 'end' %>
      <% if players.find_by(position: position).position == table_hand.first_player_position %>
        first-player-right
      <% elsif players.find_by(position: position).position == table_hand.positions[(table_hand.positions.index(table_hand.first_player_position) + 1) % players.count] %>
        second-player-right
      <% end %>
    <% end %>" data-popper-target="element" data-action="mouseenter->popper#show mouseleave->popper#hide">
      <div id="tooltip" role="tooltip" data-popper-target="tooltip">
        <%= render 'poker_tables/luck', player: players.find_by(position: position) %>
        <div id="arrow" data-popper-arrow></div>
      </div>
      <%= render 'poker_tables/player', player: players.find_by(position: position), table_hand: table_hand %>
    </div>
  </div>
<% end %>

app/views/poker_tables/_seat_top.html.erb
<% if players.find_by(position: position).nil? %>
  <% if players.exclude?(player) && player.user.balance >= poker_table.small_blind * 100 && player.user.players.active.empty? %>
    <div class="join-seat seat-top">
      <%= link_to "Join seat", poker_table_players_path(poker_table, position: position), data: { turbo_method: :post }, class: 'stretched-link' %>
    </div>
  <% else %>
    <div class="available-seat seat-top">
      <p><%= position %></p>
    </div>
  <% end %>
<% else %>
  <div class="player-container player-container-top" data-controller="popper">
    <div class="player-display player-display-top <% if !table_hand.nil? && table_hand.status != 'end' %>
      <% if players.find_by(position: position).position == table_hand.first_player_position %>
        first-player-top
      <% elsif players.find_by(position: position).position == table_hand.positions[(table_hand.positions.index(table_hand.first_player_position) + 1) % players.count] %>
        second-player-top
      <% end %>
    <% end %>" data-popper-target="element" data-action="mouseenter->popper#show mouseleave->popper#hide">
      <div id="tooltip" role="tooltip" data-popper-target="tooltip">
        <%= render 'poker_tables/luck', player: players.find_by(position: position) %>
        <div id="arrow" data-popper-arrow></div>
      </div>
      <%= render 'poker_tables/player', player: players.find_by(position: position), table_hand: table_hand %>
    </div>
  </div>
<% end %>

app/views/poker_tables/_table_item.html.erb
<div class="table-item mb-4">
  <div class="text-center">
    <h2 class='h4'><%= poker_table.name %></h2>
    <div class="poker-table mb-2">
      <div class="poker-table-overlay justify-content-center align-items-center pb-1">
        <div class="text-center">
          <p><i class="fa-solid fa-user-group"></i> <span class="text-uppercase">Max players:</span> <%= poker_table.max_players %></p>
          <div class="d-flex justify-content-center py-1">
            <% if poker_table.players.active.count.zero? %>
              <% TableHand::CARDS.dup.sample(5).each do |card| %>
                <%= image_tag "cards/#{card}.svg", class: 'table-card-item px-1' %>
              <% end %>
            <% else %>
              <% poker_table.players.active.each do |player| %>
                <div class="px-1">
                  <% if player.user.photo.attached? %>
                    <%= cl_image_tag player.user.photo.key, alt: "Picture of #{player.user.nickname}", class: "avatar" %>
                  <% else %>
                    <%= image_tag "https://avatars.dicebear.com/api/micah/#{player.user.nickname}.svg?background=%231A8A47", class: "avatar" %>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
          <p class="text-info"><i class="fa-solid fa-coins"></i> <span class="text-uppercase">Small blind:</span> <%= poker_table.small_blind %></p>
        </div>
      </div>
    </div>
  </div>
  <%= link_to "Join this table", poker_table_path(poker_table), class: "btn btn-action stretched-link" %>
</div>

app/views/poker_tables/_winner.html.erb
<div class="winner-overlay">
  <div class="winner-info">
    <% winnerhands.each do |winnerhand| %>
      <% unless winnerhand.combination.nil? %>
        <%  case winnerhand.combination[1]  %>
          <%  when 11 then trad = winnerhand.combination[1].to_s.gsub("11", "Jacks")  %>
          <%  when 12 then trad = winnerhand.combination[1].to_s.gsub("12", "Queens")  %>
          <%  when 13 then trad = winnerhand.combination[1].to_s.gsub("13", "Kings")  %>
          <%  when 14 then trad = winnerhand.combination[1].to_s.gsub!("14", "Aces")  %>
        <% end %>
        <% case winnerhand.combination[0] %>
        <% when 0 then @combo = "High Card of #{trad.nil? ? winnerhand.combination[1] : trad}"%>
        <% when 1 then @combo = "Pair of #{trad.nil? ? winnerhand.combination[1] : trad}"%>
        <% when 2 then @combo = "Double Pair with highest pair of #{trad.nil? ? winnerhand.combination[1] : trad}"%>
        <% when 3 then @combo = "Three of a kind of #{trad.nil? ? winnerhand.combination[1] : trad}"%>
        <% when 4 then @combo = "Straight with highest card of #{trad.nil? ? winnerhand.combination[1] : trad}"%>
        <% when 5 then @combo = "Flush with hightest card of #{trad.nil? ? winnerhand.combination[1] : trad}"%>
        <% when 6 then @combo = "Full House of #{trad.nil? ? winnerhand.combination[1] : trad}"%>
        <% when 7 then @combo = "Four of a kind of #{trad.nil? ? winnerhand.combination[1] : trad}"%>
        <% when 8 then @combo = "Straight Flush with highest card of #{trad.nil? ? winnerhand.combination[1] : trad}" %>
        <% when 9 then @combo = "Royal Emperor Straight Legendary Flush" %>
        <% end %>
      <% else %>
        <% @combo = "folded opponents" %>
      <% end %>
      <%# <% winnerhand.combination = @combo %>
    <% end %>

  <% if winnerhands.count == 1 %>
    <% winnerhands.each do |winnerhand| %>
      <div class="winner-avatar">
        <div class="avatar-overlay">
          <% if winnerhand.player.user.photo.attached? %>
            <%= cl_image_tag winnerhand.player.user.photo.key, alt: "Picture of #{winnerhand.player.user.nickname}", class: "avatar-large"%>
          <% else %>
            <%= image_tag "https://avatars.dicebear.com/api/micah/#{winnerhand.player.user.nickname}.svg?background=%231A8A47", class: "avatar-large" %>
          <% end %>
        </div>
      </div>

        <% if winnerhand.player == player %>
          <p class="h2">Congratulations!</p>
          <h2 class="h1 text-info">You won <%= winnerhand.table_hand.pot %> coins!</h2>
        <% else %>
          <p class="h2">Too bad...</p>
          <h2 class="h1 text-black"><%= winnerhand.player.user.nickname  %> won</h2>
        <% end %>




        <%# <h3 class="pot"><i class="fa-solid fa-coins"></i> <%= winnerhand.table_hand.pot %>
        <h4><%= @combo %></h4>
        <div class="cardsandopponents d-flex justify-content-center align-items-center">
          <div class="winner-cards">
            <%= image_tag "cards/#{winnerhand.player_card1}.svg", class: 'winner-card', id: 'winner-card1' %>
            <%= image_tag "cards/#{winnerhand.player_card2}.svg", class: 'winner-card', id: 'winner-card2' %>
          </div>
          <div class="opponents justify-content-evenly ms-4 d-flex">
            <% poker_table.table_hands.last.players.each do |opponent| %>
              <% unless winnerhands.include?(opponent.player_hands.last) %>
                <%= render 'poker_tables/opponent_card', player: opponent %>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="table-hand-recap">

          <% unless winnerhand.table_hand.table_card1.nil? %>
            <%= image_tag "cards/#{winnerhand.table_hand.table_card1}.svg", class: 'table-card' %>
            <%= image_tag "cards/#{winnerhand.table_hand.table_card2}.svg", class: 'table-card' %>
            <%= image_tag "cards/#{winnerhand.table_hand.table_card3}.svg", class: 'table-card' %>
          <% else %>
            <%= image_tag "cards/1B.svg", class: 'table-card' %>
            <%= image_tag "cards/1B.svg", class: 'table-card' %>
            <%= image_tag "cards/1B.svg", class: 'table-card' %>
          <% end %>
          <% unless winnerhand.table_hand.table_card4.nil? %>
            <%= image_tag "cards/#{winnerhand.table_hand.table_card4}.svg", class: 'table-card' %>
          <% else %>
            <%= image_tag "cards/1B.svg", class: 'table-card' %>
          <% end %>
          <% unless winnerhand.table_hand.table_card5.nil? %>
            <%= image_tag "cards/#{winnerhand.table_hand.table_card5}.svg", class: 'table-card' %>
          <% else %>
            <%= image_tag "cards/1B.svg", class: 'table-card' %>
          <% end %>
        </div>
    <% end %>

  <% end %>


  <% if winnerhands.count > 1 %>
    <% winnerhand = winnerhands.first %>
        <div class="winner-avatar">
          <div class="avatar-overlay">
            <% if player.user.photo.attached? %>
              <%= cl_image_tag winnerhand.user.photo.key, alt: "Picture of #{player.user.nickname}", class: "avatar-large"%>
            <% else %>
              <%= image_tag "https://avatars.dicebear.com/api/micah/#{player.user.nickname}.svg?background=%231A8A47", class: "avatar-large" %>
            <% end %>
          </div>
        </div>

          <% if winnerhands.include?(player.player_hands.last) %>
            <p class="h2">Pot splitted!</p>
            <%# <h2 class="h1 text-info">You won, <%= winnerhand.player.user.nickname %>
          <% else %>
            <p class="h2">Too bad...</p>
            <h2 class="h1 text-black"><%= winnerhand.player.user.nickname  %> won</h2>
          <% end %>




          <h3 class="pot"><i class="fa-solid fa-coins"></i> <%= (winnerhand.table_hand.pot / 2) %> coins</h3>
          <div class="cardsandcombination d-flex align-items-center">
            <div class="winner-cards">
              <%= image_tag "cards/#{winnerhand.player_card1}.svg", class: 'winner-card', id: 'winner-card1' %>
              <%= image_tag "cards/#{winnerhand.player_card2}.svg", class: 'winner-card', id: 'winner-card2' %>
            </div>
            <div class="combination">
              <h5><%= @combo %></h5>
            </div>
          </div>
          <div class="table-hand-recap">

            <% unless winnerhand.table_hand.table_card1.nil? %>
              <%= image_tag "cards/#{winnerhand.table_hand.table_card1}.svg", class: 'table-card' %>
              <%= image_tag "cards/#{winnerhand.table_hand.table_card2}.svg", class: 'table-card' %>
              <%= image_tag "cards/#{winnerhand.table_hand.table_card3}.svg", class: 'table-card' %>
            <% else %>
              <%= image_tag "cards/1B.svg", class: 'table-card' %>
              <%= image_tag "cards/1B.svg", class: 'table-card' %>
              <%= image_tag "cards/1B.svg", class: 'table-card' %>
            <% end %>
            <% unless winnerhand.table_hand.table_card4.nil? %>
              <%= image_tag "cards/#{winnerhand.table_hand.table_card4}.svg", class: 'table-card' %>
            <% else %>
              <%= image_tag "cards/1B.svg", class: 'table-card' %>
            <% end %>
            <% unless winnerhand.table_hand.table_card5.nil? %>
              <%= image_tag "cards/#{winnerhand.table_hand.table_card5}.svg", class: 'table-card' %>
            <% else %>
              <%= image_tag "cards/1B.svg", class: 'table-card' %>
            <% end %>
          </div>
      <%# <% end %>

  <% end %>



    <% if player == winnerhands.last.player%>
      <% if poker_table.players.active.count >= 2 %>
        <%= link_to "Restart", table_hands_path(poker_table_id: poker_table.id), data: { turbo_method: :post }, class: 'btn btn-action' %>
      <% else %>
        <%= link_to "Back to the table", table_hand_back_path(poker_table_id: poker_table.id, table_hand_id: poker_table.table_hands.last.id), data: { turbo_method: :patch }, class: 'btn btn-action' %>
      <% end %>
    <% else %>
      <p class="mb-0 text-primary">Waiting for <%= winnerhands.last.player.user.nickname %> to restart the game...</p>
    <% end %>
  </div>
</div>

app/views/poker_tables/index.html.erb
<div class="coins-left"></div>
<div class="coins-right"></div>
<div class="container py-4">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <h1>It’s raining coins</h1>
      <p class="find-table-ok">Select a table and win the pot</p>
      <div class="d-flex align-items-center mb-3">
        <small class="text-uppercase text-primary">Filter by: </small>
        <div class="ms-2 filters">
          <div class="dropdown">
            <button class="dropbtn">Filter Players ↓ <%= @max_players %></button>
            <div class="dropdown-content">
              <%= link_to "Any", poker_tables_path %>
              <%= link_to "5", poker_tables_path(max_players: 5) %>
              <%= link_to "7", poker_tables_path(max_players: 7) %>
              <%= link_to "9", poker_tables_path(max_players: 9) %>
            </div>
          </div>
          <div class="dropdown">
            <button class="dropbtn">Filter Blinds ↓ <%= @small_blind %> </button>
            <div class="dropdown-content">
              <%= link_to "Any", poker_tables_path %>
              <%= link_to "1-2", poker_tables_path(small_blind: 1) %>
              <%= link_to "5-10", poker_tables_path(small_blind: 5) %>
              <%= link_to "10-20", poker_tables_path(small_blind: 10) %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <% @poker_tables.each do |poker_table| %>
          <div class="col-md-6 col-xl-4">
            <%= render "table_item", poker_table: poker_table %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/poker_tables/show.html.erb
<% if current_user.players.active.empty? %>
  <% @player = Player.create(user: current_user) %>
<%  else %>
  <% @player = current_user.players.active.first %>
<% end %>

<div data-controller="player-subscription" data-player-subscription-player-id-value="<%= @player.id %>">
  <%= render 'show', poker_table: @poker_table, players: @players, positions: @positions, table_hand: @table_hand, player: @player %>
</div>